## Designer-facing sound slots and per-cue mix settings.
## Empty stream slots intentionally fall back to the procedural preview sounds
## generated by SoundEffectSystem.
class_name SoundEffectLibrary
extends Resource

const UI_OPERATION: StringName = &"ui_operation"
const CONSTRUCTION: StringName = &"construction"
const ATTACK: StringName = &"attack"
const HIT: StringName = &"hit"
const DEATH: StringName = &"death"
const VICTORY: StringName = &"victory"
const DEFEAT: StringName = &"defeat"

const EVENT_IDS: Array[StringName] = [
	UI_OPERATION,
	CONSTRUCTION,
	ATTACK,
	HIT,
	DEATH,
	VICTORY,
	DEFEAT,
]

@export_group("Streams")
@export var ui_operation: AudioStream
@export var construction: AudioStream
@export var attack: AudioStream
@export var hit: AudioStream
@export var death: AudioStream
@export var victory: AudioStream
@export var defeat: AudioStream

@export_group("Cue Volume (dB)")
@export_range(-60.0, 6.0, 0.5) var ui_operation_volume_db: float = -13.0
@export_range(-60.0, 6.0, 0.5) var construction_volume_db: float = -6.0
@export_range(-60.0, 6.0, 0.5) var attack_volume_db: float = -11.0
@export_range(-60.0, 6.0, 0.5) var hit_volume_db: float = -12.0
@export_range(-60.0, 6.0, 0.5) var death_volume_db: float = -7.0
@export_range(-60.0, 6.0, 0.5) var victory_volume_db: float = -3.0
@export_range(-60.0, 6.0, 0.5) var defeat_volume_db: float = -4.0

@export_group("Variation")
@export_range(0.0, 0.25, 0.005) var ui_pitch_variation: float = 0.015
@export_range(0.0, 0.25, 0.005) var construction_pitch_variation: float = 0.035
@export_range(0.0, 0.25, 0.005) var attack_pitch_variation: float = 0.08
@export_range(0.0, 0.25, 0.005) var hit_pitch_variation: float = 0.11
@export_range(0.0, 0.25, 0.005) var death_pitch_variation: float = 0.045


func get_stream(event_id: StringName) -> AudioStream:
	match event_id:
		UI_OPERATION:
			return ui_operation
		CONSTRUCTION:
			return construction
		ATTACK:
			return attack
		HIT:
			return hit
		DEATH:
			return death
		VICTORY:
			return victory
		DEFEAT:
			return defeat
		_:
			return null


func get_volume_db(event_id: StringName) -> float:
	match event_id:
		UI_OPERATION:
			return ui_operation_volume_db
		CONSTRUCTION:
			return construction_volume_db
		ATTACK:
			return attack_volume_db
		HIT:
			return hit_volume_db
		DEATH:
			return death_volume_db
		VICTORY:
			return victory_volume_db
		DEFEAT:
			return defeat_volume_db
		_:
			return 0.0


func get_pitch_variation(event_id: StringName) -> float:
	match event_id:
		UI_OPERATION:
			return ui_pitch_variation
		CONSTRUCTION:
			return construction_pitch_variation
		ATTACK:
			return attack_pitch_variation
		HIT:
			return hit_pitch_variation
		DEATH:
			return death_pitch_variation
		_:
			return 0.0


func supports(event_id: StringName) -> bool:
	return EVENT_IDS.has(event_id)
